### ISSUE TITLE
Corregir path de apertura para huayra-visor-manual

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/huayra-bullets#3]
Como ahora el visor de manual se va a poder abrir indicando solamente el nombre de la página (o realizará una búsqueda), tendíamos que cambiar las rutas dentro del asistente de primeros pasos.

Ahora, el asistente de primeros pasos usa rutas completas.

https://github.com/HuayraLinux/huayra-visor-manual/issues/9

**Comment by iglosiggio** [comment]
Hasta donde recuerdo estaba todo andando porque soporta los dos estilos de path. Cierro hasta que estemos testeando con el manual de H4
