### ISSUE TITLE
Número de versión de Huayra desactualizada

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-bullets#4]
Actualizar los bullets en un branch para Huarya 3.2 y generar actualización en sud-updates 

También ahora para 4.x comenzar a realizar las modificaciones pertinentes

**Comment by ftoledo** [comment]
Versión 3.2 está oK. (estaba desactualizado el paquete en zonda). Queda entonces ir haciendo las modificaciones para la 4.x

**Comment by matiasdelellis** [comment]
Podemos cerrarlo.. 4 no existe 👻 , y 5 ya esta..
